OWNERS
-Adding proper approvers
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Adding proper approvers

aws-sqs-sink/README.adoc, aws-sqs-sink/pom.xml, aws-sqs-sink/properties.adoc, aws-sqs-sink/src/main/docker/Dockerfile.jvm, aws-sqs-sink/src/main/docker/Dockerfile.legacy-jar, aws-sqs-sink/src/main/docker/Dockerfile.native, aws-sqs-sink/src/main/docker/Dockerfile.native-micro, aws-sqs-sink/src/main/kubernetes/kubernetes.yml, aws-sqs-sink/src/main/resources/META-INF/LICENSE.txt, aws-sqs-sink/src/main/resources/META-INF/NOTICE.txt, aws-sqs-sink/src/main/resources/application.properties, aws-sqs-sink/src/main/resources/camel/kn-connector-sink.yaml, aws-sqs-sink/src/main/resources/knative.json, pom.xml
- as per title
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Adding s3 sqs sink

aws-sqs-sink/src/main/resources/application.properties
Similar to https://github.com/knative-extensions/eventing-integrations/pull/13
also related to https://github.com/knative-extensions/eventing-integrations/issues/14
=> adding required setting to properties file

aws-s3-sink/pom.xml, aws-s3-sink/src/test/java/dev/knative/eventing/connector/AwsS3SinkTest.java, aws-s3-sink/src/test/java/dev/knative/eventing/connector/LocalstackTestResource.java, aws-sqs-sink/pom.xml, aws-sqs-sink/src/test/java/dev/knative/eventing/connector/AwsSqsSinkTest.java, aws-sqs-sink/src/test/java/dev/knative/eventing/connector/LocalstackTestResource.java
- Add test for AWS S3 sink
- Add test for AWS SQS sink
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Add AWS sink tests

aws-ddb-streams-source/pom.xml, aws-s3-sink/pom.xml, aws-s3-source/pom.xml, aws-sqs-sink/pom.xml, aws-sqs-source/pom.xml, log-sink/pom.xml, pom.xml, timer-source/pom.xml, tools/archetype-sink/pom.xml, tools/archetype-sink/src/main/resources/archetype-resources/pom.xml, tools/archetype-source/pom.xml, tools/archetype-source/src/main/resources/archetype-resources/pom.xml, tools/maven-plugin/pom.xml, tools/pom.xml
- Remove kn- prefix from module names
/cc @matzew
=> Remove kn- prefix from module names

aws-ddb-streams-source/pom.xml, log-sink/pom.xml
Continue on @dsimansk work
/assign @christophd
=> Removing connector image prefix

test/presubmit-tests.sh, test/presubmit-tests.sh.tmpl
- Add placeholder presubmit test script
Related to image push issue: #6
Fixes the nightly error: https://prow.knative.dev/view/gs/knative-prow/logs/nightly_eventing-integrations_main_periodic/1845390113039716352
/cc @matzew
=> Add placeholder presubmit test script

pom.xml
-  Add latest tag build configuration
Related to #6 
/cc @matzew
=> Add latest tag build configuration

README.adoc, common/utils/src/main/java/dev/knative/eventing/source/KnativeHttpClientOptions.java
Users can set multiple CA cert paths as comma delimited String value on the environment variables
/kind enhancement
Fixes #32
```release-note
```
**Docs**
```docs
```
=> fix(#32): Support multiple CA certs

aws-sns-sink/pom.xml, aws-sns-sink/src/test/java/dev/knative/eventing/connector/AwsSnsSinkTest.java, aws-sns-sink/src/test/java/dev/knative/eventing/connector/LocalstackTestResource.java, aws-sns-sink/src/test/resources/application.properties, tools/archetype-sink/src/main/resources/archetype-resources/pom.xml, tools/archetype-source/src/main/resources/archetype-resources/pom.xml
- Add unit tests that uses the AWS SNS sink, verify that data gets published with an AWS SQS notification endpoint subscriber
- Remove the "connector-" prefix in Maven module names
/kind enhancement
Relates to #39
```release-note
```
**Docs**
```docs
```
=> Add AWS SNS Sink tests

aws-ddb-streams-source/src/test/resources/application.properties, aws-s3-sink/src/test/resources/application.properties, aws-s3-source/src/test/resources/application.properties, aws-sqs-sink/src/test/resources/application.properties, aws-sqs-source/src/test/resources/application.properties, log-sink/src/test/resources/application.properties, timer-source/src/test/resources/application.properties
- Ignore warnings during test execution related to Citrus split packages
/kind enhancement
```release-note
```
**Docs**
```docs
```
=> Ignore warnings during test execution related to Citrus split packages

aws-ddb-streams-source/pom.xml, aws-s3-sink/pom.xml, aws-s3-source/pom.xml, aws-sns-sink/pom.xml, aws-sqs-sink/pom.xml, aws-sqs-source/pom.xml, log-sink/pom.xml, pom.xml, timer-source/pom.xml, tools/archetype-sink/src/main/resources/archetype-resources/pom.xml, tools/archetype-source/src/main/resources/archetype-resources/pom.xml, tools/maven-plugin/src/main/java/dev/knative/eventing/connector/maven/plugin/GenerateConnectorSpecMojo.java
- Update to Quarkus 3.17.0 and Camel 4.9.0
/kind enhancement
```release-note
```
**Docs**
```docs
```
=> Update to Quarkus 3.17.0 and Camel 4.9.0

hack/release.sh
- Fix generated ConfigMap indentation
A small and quick fix PTAL,
/cc @matzew
=> Fix generated ConfigMap indentation

aws-ddb-streams-source/src/test/resources/citrus-application.properties, aws-s3-sink/src/test/resources/citrus-application.properties, aws-s3-source/src/test/resources/citrus-application.properties, aws-sns-sink/src/test/resources/citrus-application.properties, aws-sqs-sink/src/test/resources/citrus-application.properties, aws-sqs-source/src/test/resources/citrus-application.properties, log-sink/src/test/resources/citrus-application.properties, pom.xml, timer-source/src/test/resources/citrus-application.properties
- Update to Citrus 4.5.1
- Use generic Docker registry mirror for Testcontainers modules
/kind <kind>
```release-note
```
**Docs**
```docs
```
=> Update to Citrus 4.5.1

aws-ddb-streams-source/src/main/resources/application.properties, aws-s3-sink/src/main/resources/application.properties, aws-s3-source/src/main/resources/application.properties, aws-sns-sink/src/main/resources/application.properties, aws-sqs-sink/src/main/resources/application.properties, aws-sqs-source/src/main/resources/application.properties
- Issue to require empty default values for properties has been fixed in Apache Camel 4.9.0
Fixes #14
```release-note
```
**Docs**
```docs
```
=> fix(#14): Remove obsolete empty default property values

aws-ddb-streams-source/pom.xml, aws-s3-sink/pom.xml, aws-s3-source/pom.xml, aws-sns-sink/pom.xml, aws-sqs-sink/pom.xml, aws-sqs-source/pom.xml, log-sink/pom.xml, timer-source/pom.xml, tools/archetype-sink/src/main/resources/archetype-resources/pom.xml, tools/archetype-source/src/main/resources/archetype-resources/pom.xml
- Only need camel-quarkus-knative since Camel Quarkus 3.17
```release-note
```
**Docs**
```docs
```
=> Remove obsolete camel-quarkus-knative-producer dependency

transform-jsonata/README.md, transform-jsonata/jsonata.js, transform-jsonata/package.json, transform-jsonata/pnpm-lock.yaml
It uses the standard Knative configurations `config-tracing` format passed through env variable
See screenshot
=> Jsonata: Support tracing

test/presubmit-tests.sh
- Exec build-tests only in presubmit-tests.sh
/cc @matzew @pierDipi
=> Exec build-tests only in presubmit-tests.sh

go.mod, go.sum
- Upgrade knative/hack package
/cc @gauron99
=> Upgrade knative/hack package

hack/release.sh
- Fix release script to respect KO_DOCKER_REPO
/cc @matzew
=> Fix release script to respect KO_DOCKER_REPO

aws-ddb-streams-source/src/test/java/dev/knative/eventing/connector/AwsDdbStreamsSourceTest.java, aws-s3-source/src/test/java/dev/knative/eventing/connector/AwsS3SourceTest.java, aws-s3-source/src/test/java/dev/knative/eventing/connector/ssl/AwsS3SourceSSLTest.java, aws-sqs-source/src/test/java/dev/knative/eventing/connector/AwsSqsSourceTest.java, pom.xml, timer-source/src/test/java/dev/knative/eventing/connector/TimerSourceTest.java, timer-source/src/test/java/dev/knative/eventing/connector/oidc/TimerSourceOIDCTest.java, timer-source/src/test/java/dev/knative/eventing/connector/ssl/TimerSourceSSLTest.java
Update dependency versions
- Camel 4.11.0
- Quarkus 3.22.1
- Citrus 4.6.0
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> chore(deps): Update dependency versions

README.adoc, tools/archetype-sink/src/main/resources/archetype-resources/pom.xml
- Improve README how to use Maven archetypes
```release-note
```
**Docs**
```docs
```
=> Fix sink Maven archetype and improve documentation

aws-eventbridge-sink/README.adoc, aws-eventbridge-sink/pom.xml, aws-eventbridge-sink/properties.adoc, aws-eventbridge-sink/properties.yaml, aws-eventbridge-sink/src/main/docker/Dockerfile.jvm, aws-eventbridge-sink/src/main/docker/Dockerfile.legacy-jar, aws-eventbridge-sink/src/main/docker/Dockerfile.native, aws-eventbridge-sink/src/main/docker/Dockerfile.native-micro, aws-eventbridge-sink/src/main/kubernetes/kubernetes.yml, aws-eventbridge-sink/src/main/resources/META-INF/LICENSE.txt, aws-eventbridge-sink/src/main/resources/META-INF/NOTICE.txt, aws-eventbridge-sink/src/main/resources/application.properties, aws-eventbridge-sink/src/main/resources/camel/sink.yaml, aws-eventbridge-sink/src/main/resources/knative.json, aws-eventbridge-sink/src/test/java/dev/knative/eventing/connector/AwsEventBridgeSinkTest.java, aws-eventbridge-sink/src/test/resources/application.properties, aws-eventbridge-sink/src/test/resources/citrus-application.properties, pom.xml
- Add new AWS EventBridge sink
/kind <kind>
Fixes #96
```release-note
```
**Docs**
```docs
```
=> fix(#96): Add AWS EventBridge sink
